### ISSUE TITLE
Please fix the example config

### ISSUE THREAD

**Issue by Turtdle** [UnnamedCheese/CrackLaser#1]
Please fix the example config. Thanks

**Comment by Porama6400** [comment]
Link in the plugin page is fixed

If you don't want to go there, here's the example config:
https://github.com/UnnamedCheese/CrackLaser/blob/master/Laser.yml

**Comment by Turtdle** [comment]
If you don't mind, can you explain these:

        ppb
        hitstop
        trigger
        shoot-aim
        damage-aim

and whats the difference between
        distance
        view-distance
Thanks a bunch!

**Comment by Porama6400** [comment]
I wrote this wiki quite a while ago
https://github.com/UnnamedCheese/CrackLaser/wiki/Configuration

Hope it is helpful

Anyway currently I'm quite busy, if I have time I'll recode cracklaser so it's easier to use
